# Generated by Django 5.2.3 on 2025-06-30 04:17

from django.db import migrations

def create_missing_profiles(apps, schema_editor):
    """
    Finds all User objects that do not have a related Profile
    and creates a Profile for them.
    """
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('users', 'Profile')

    # Using get_or_create is a safe way to ensure we don't try to create
    # a profile that might already exist for some users.
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # This tells Django to run our Python script during the migration.
        migrations.RunPython(create_missing_profiles),
    ]