# Generated by Django 5.2.3 on 2025-06-30 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendrequest'),
        ('users', '0003_create_missing_profiles'),
    ]

    operations = [
    ]
