# Generated by Django 5.2.3 on 2025-07-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_0002_friendrequest_0003_create_missing_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short biography describing your work and research interests.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, help_text='A short headline, e.g., Quantum Biologist at Chimera University', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, help_text='Your university, company, or institution.', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, help_text='Your full name, e.g., Dr. Eva Rostova', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True, help_text='A link to your personal website, blog, or portfolio.'),
        ),
    ]
