# Generated by Django 5.2.3 on 2025-07-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_bio_profile_headline_profile_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_picture',
            field=models.ImageField(default='banner_pics/default.jpg', upload_to='banner_pics'),
        ),
    ]
