# Generated by Django 5.2.3 on 2025-07-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_banner_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='research_interests',
            field=models.TextField(blank=True, help_text='Comma-separated list of your research interests (e.g., Quantum Computing, Machine Learning).'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of your skills (e.g., Python, Data Analysis, R).'),
        ),
    ]
