# Generated by Django 5.2.3 on 2025-06-25 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_accessrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
