# Generated by Django 5.2.3 on 2025-06-26 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comment_read_by_task_read_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
