# Generated by Django 5.2.3 on 2025-06-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_comment_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
