# Generated by Django 5.2.3 on 2025-06-27 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_task_assignees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignees',
        ),
    ]
