# Generated by Django 5.2.3 on 2025-06-27 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_task_assignees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='marked_by',
            field=models.ManyToManyField(blank=True, related_name='marked_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
