# Generated by Django 5.2.3 on 2025-06-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='role_at_ban',
            field=models.CharField(default='viewer', max_length=10),
        ),
    ]
