# Generated by Django 5.2.3 on 2025-07-04 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_projectinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaltodo',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='personaltodo',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personaltodo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
