# Generated by Django 5.2.3 on 2025-06-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('authors', models.CharField(max_length=1024)),
                ('abstract', models.TextField()),
                ('arxiv_id', models.CharField(max_length=100, unique=True)),
                ('publication_date', models.DateField()),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
